### PR TITLE
Create dino.md

### PR DESCRIPTION
**Pull request by sparkyfina**
Created new mark file - dino.md

### CODE REVIEW

**Comment by drguthals** [comment]
Thank you for coming! Welcome to the community :D

**Comment by sparkyfina** [comment]
ZSent from my Sprint Samsung Galaxy S8.
-------- Original message --------From: Sarah Guthals <notifications@github.com> Date: 9/24/20  1:42 PM  (GMT-05:00) To: sguthals/talkswithdrg <talkswithdrg@noreply.github.com> Cc: Dino Vitale <sparkyfina@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [sguthals/talkswithdrg] Create dino.md (#25) 
Thank you for coming! Welcome to the community :D

**Comment by sparkyfina** [comment]
XaeasZSent from my Sprint Samsung Galaxy S8.
-------- Original message --------From: Sarah Guthals <notifications@github.com> Date: 9/24/20  1:42 PM  (GMT-05:00) To: sguthals/talkswithdrg <talkswithdrg@noreply.github.com> Cc: Dino Vitale <sparkyfina@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [sguthals/talkswithdrg] Create dino.md (#25) 
Thank you for coming! Welcome to the community :D

**Comment by sparkyfina** [comment]
AEssTuh ASent from my Sprint Samsung Galaxy S8.
-------- Original message --------From: Sarah Guthals <notifications@github.com> Date: 9/24/20  1:42 PM  (GMT-05:00) To: sguthals/talkswithdrg <talkswithdrg@noreply.github.com> Cc: Dino Vitale <sparkyfina@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [sguthals/talkswithdrg] Create dino.md (#25) 
Thank you for coming! Welcome to the community :D

**Pull request merged**
