### PR TITLE
First Pull request thans

### PR DESCRIPTION
**Pull request by HallSimonHall**

### CODE REVIEW

**Comment by HallSimonHall** [comment]
Think I had a typo there with that pull request commnent.

**Review by drguthals — APPROVED** [review]
Haha - FACTS

Welcome to the community!

**Comment by drguthals** [comment]
While in this scenario adding a description is a little redundant, it is always a good idea to have a description in a PR :D

**Comment by HallSimonHall** [comment]
I agree, and thanks for the reminder.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
